const addContent_1 = document.querySelector('.listElement-1');
const addContent_2 = document.querySelector('.listElement-2');
const addContent_3 = document.querySelector('.listElement-3');
contentOne = "1";
contentTwo = "2";
contentThree = "3";
addContent_1.innerHTML = contentOne;
addContent_2.innerHTML = contentTwo;
addContent_3.innerHTML = contentThree;